### ISSUE TITLE
Which pin coding method are you using？

### ISSUE THREAD

**Issue by LandonWong** [derekmulcahy/xvcpi#3]
Hi,

I am using your project and it is great! I successfully opened the hardware server, but the device cannot be found. My guess is that the pins connected to the board correspond to errors. Which pin coding method do you use? Is it BCM2835? But pin 23 is not GND.

Thanks

**Comment by AndersBNielsen** [comment]
My guess would be it’s GPIO numbers and header pin 25 - not 23. That would make sense.

**Comment by derekmulcahy** [comment]
It is GPIO numbers and pin23 is not GND but pin 20 is. Sorry for the typo.
